package org.example;

import java.awt.*;
import java.util.Calendar;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

public class Book {
    private int idBook;
    private String Title;
    private int PublicationYear;
    private String Language;

    private int NbPages;
    private int idCategory;
    private int idAuthor;
    private int rating;
    private float price;
    private int bookimage;
    public Book(int idBook, String title, int publicationYear, String language, int nbPages, int idcategory, int idAuthor, int rating, float price, int bookimage) {
        this.idBook = idBook;
        this.Title = title;
        this.PublicationYear = publicationYear;
        this.Language = language;
        this.NbPages = nbPages;
        this.idCategory = idcategory;
        this.idAuthor = idAuthor;
        this.rating = rating;
        this.price = price;
        this.bookimage = bookimage;
    }
    public Book() {
        this.idBook = 0; // Default value for int
        this.Title = "Default Title"; // Default value for String
        this.PublicationYear = 0; // Default value for int
        this.Language = "English"; // Default value for String
        this.NbPages = 0; // Default value for int
        this.idCategory = 0; // Default value for int
        this.idAuthor = 0; // Default value for int
        this.rating = 0; // Default value for int
        this.price = 0; // Default value for int
        this.bookimage = 0; // Default value for String
    }
    public Book(int idBook, int idAuthor) {
        this.idBook = idBook;
        String[] LTitles = {
                "To Kill a Mockingbird",
                "1984",
                "The Great Gatsby",
                "Pride and Prejudice",
                "The Catcher in the Rye",
                "The Lord of the Rings",
                "Animal Farm",
                "Brave New World",
                "Fahrenheit 451",
                "The Grapes of Wrath",
                "The Hobbit",
                "War and Peace",
                "Moby-Dick",
                "One Hundred Years of Solitude",
                "The Adventures of Huckleberry Finn",
                "The Chronicles of Narnia",
                "Crime and Punishment",
                "The Kite Runner",
                "The Picture of Dorian Gray",
                "Gone with the Wind",
                "Les Misérables",
                "Anna Karenina",
                "The Alchemist",
                "The Scarlet Letter",
                "Slaughterhouse-Five",
                "The Stranger",
                "Frankenstein",
                "Great Expectations",
                "The Odyssey",
                "The Road",
                "A Tale of Two Cities",
                "Beloved",
                "The Handmaid's Tale",
                "Dracula",
                "Wuthering Heights",
                "Little Women",
                "Jane Eyre",
                "Don Quixote",
                "Catch-22",
                "The Sun Also Rises",
                "The Brothers Karamazov",
                "Heart of Darkness",
                "The Count of Monte Cristo",
                "The Iliad",
                "A Clockwork Orange",
                "East of Eden",
                "The Bell Jar",
                "Invisible Man",
                "Unlocking Android",
                "Android in Action, Second Edition",
                "Specification by Example",
                "Flex 3 in Action",
                "Flex 4 in Action",
                "Collective Intelligence in Action",
                "Zend Framework in Action",
                "Flex on Java",
                "Griffon in Action",
                "OSGi in Depth",
                "Flexible Rails",
                "Hello! Flex 4",
                "Coffeehouse",
                "Team Foundation Server 2008 in Action",
                "Brownfield Application Development in .NET",
                "MongoDB in Action",
                "Distributed Application Development with PowerBuilder 6.0",
                "Jaguar Development with PowerBuilder 7",
                "Taming Jaguar",
                "3D User Interfaces with Java 3D",
                "Hibernate in Action",
                "Hibernate in Action (Chinese Edition)",
                "Java Persistence with Hibernate",
                "JSTL in Action",
                "iBATIS in Action",
                "Designing Hard Software",
                "Hibernate Search in Action",
                "jQuery in Action",
                "jQuery in Action, Second Edition",
                "Building Secure and Reliable Network Applications",
                "Ruby for Rails",
                "The Well-Grounded Rubyist",
                "Website Owner's Manual",
                "ASP.NET 4.0 in Practice",
                "Hello! Python",
                "PFC Programmer's Reference Manual",
                "Graphics File Formats",
                "Visual Object Oriented Programming",
                "iOS in Practice",
                "iPhone in Action",
                "Silverlight 2 in Action",
                "The Quick Python Book, Second Edition",
                "Internet and Intranet Applications with PowerBuilder 6",
                "Practical Methods for Your Year 2000 Problem",
                "Mobile Agents",
                "Spring Dynamic Modules in Action",
                "SQL Server 2008 Administration in Action",
                "Android in Practice",
                "Object Oriented Perl",
                "GWT in Practice",
                "Ajax in Action",
                "Ajax in Practice",
                "Prototype and Scriptaculous in Action",
                "POJOs in Action",
                "Data Munging with Perl",
                "Hello! HTML5 & CSS3",
                "Seam in Action",
                "Wicket in Action",
                "Open Source SOA",
                "Struts 2 in Action",
                "Essential Guide to Peoplesoft Development and Customization",
                ".NET Multithreading",
                "SCWCD Exam Study Kit Second Edition",
                "Spring Roo in Action",
                "SOA Governance in Action",
                "RSS and Atom in Action",
                "LDAP Programming, Management and Integration",
                "Mule in Action",
                "Java Foundation Classes",
                "Managing Components with Modeler",
                "Command-line Processing with CLI",
                "Understanding and Using Chain",
                "Working with the Logging and Discovery Components",
                "Uploading files with FileUpload",
                "Handling Protocols with the Net Component",
                "XML Parsing with Digester",
                "JXPath and Betwixt: Working with XML",
                "Validating Data with Validator",
                "Enhancing Java Core Libraries with Collections",
                "Enhancing Java Core Libraries with BeanUtils and Lang",
                "Pool and DBCP: Creating and Using Object Pools",
                "Python and Tkinter Programming",
                "Microsoft.NET for Programmers",
                "Grails in Action",
                "Up to Speed with Swing, Second Edition",
                "OSGi in Action",
                "GWT in Action",
                "The Quick Python Book",
                "SharePoint 2010 Site Owner's Manual",
                "Java Development with Ant",
                "Lucene in Action",
                "Lucene in Action, Second Edition",
                "PowerBuilder 6.0 Questions & Answers",
                "The Awesome Power of PowerJ",
                "The Awesome Power of Power++",
                "Azure in Action",
                "Distributed Agile in Action",
                "Metaprogramming in .NET",
                "Portlets and Apache Portals",
                "Code Generation in Action",
                "Illustrated Guide to HTTP",
                "Agile ALM",
                "Java Network Programming, Second Edition",
                "Struts in Action",
                "Camel in Action",
                "Taming Text",
                "JBoss in Action",
                "Gnuplot in Action",
                "Extending and Embedding Perl",
                "iOS 4 in Action",
                "Elements of Programming with Perl",
                "Learn Windows PowerShell in a Month of Lunches",
                "R in Action",
                "Android in Practice",
                "SOA Security",
                "Rails 3 in Action",
                "Continuous Integration in .NET",
                "Technology Paradise Lost",
                "Kermit 95+",
                "Laszlo in Action",
                "Groovy in Action",
                "Groovy in Action, Second Edition",
                "Object Technology Centers of Excellence",
                "Test Driven",
                "Effective Unit Testing",
                "Making Java Groovy",
                "The Awesome Power of Direct3D/DirectX",
                "Practical Software Requirements",
                "NHibernate in Action",
                "Microsoft Reporting Services in Action",
                "AspectJ in Action",
                "AspectJ in Action, Second Edition",
                "Hadoop in Action",
                "SQR in PeopleSoft and Other Applications",
                "SQR in PeopleSoft and Other Applications, Second Edition",
                "F# in Action",
                "Tuscany SCA in Action",
                "Client/Server Yellow Pages",
                "Object Oriented Application Frameworks",
                "Tapestry in Action",
                "WebWork in Action",
                "MacRuby in Action",
                "Erlang and OTP in Action",
                "SharePoint 2007 Developer's Guide to Business Data Catalog",
                "Doing IT Right",
                "Adobe AIR in Action",
                "Ant in Action",
                "Restlet in Action",
                "iText in Action",
                "iText in Action, Second Edition",
                "Power-3D",
                "SNA and TCP/IP Enterprise Networking",
                "Subversion in Action",
                "Minimal Perl",
                "Distributed Programming with Java",
                "Comprehensive Networking Glossary and Acronym Guide",
                "JavaServer Faces in Action",
                "LINQ in Action",
                "Internet BBSs",
                "Algorithms of the Intelligent Web",
                "JUnit in Action",
                "Tika in Action",
                "Ruby in Practice",
                "Inside LotusScript",
                "Maximum MIDI",
                "Planning and Managing ATM Networks",
                "Client/Server Applications on ATM Networks",
                "JavaFX in Action",
                "Entity Framework 4 in Action",
                "ASP.NET 2.0 Web Parts in Action",
                "Sass and Compass in Action",
                "Core OWL 5.0",
                "Advanced OWL 5.0",
                "Server-Based Java Programming",
                "SQL Server MVP Deep Dives",
                "SQL Server MVP Deep Dives",
                "SQL Server MVP Deep Dives",
                "PostGIS in Action",
                "Programming Mac OS X",
                "The Art of Unit Testing",
                "Mahout in Action",
                "ASP.NET MVC in Action",
                "ASP.NET MVC 2 in Action",
                "ASP.NET MVC 4 in Action",
                "EJB 3 in Action",
                "EJB 3 in Action, Second Edition",
                "Explorer's Guide to the Semantic Web",
                "Practical LotusScript",
                "Domino Development with Java",
                "Windows PowerShell in Action",
                "Windows PowerShell in Action, Second Edition",
                "Silverlight 4 in Action, Revised Edition",
                "Silverlight 5 in Action",
                "Hibernate Quickly",
                "Generative Art",
                "Windows Phone 7 in Action",
                "Lift in Action",
                "Web Development with Apache and Perl",
                "Real-World Functional Programming",
                "Machine Learning in Action",
                "Dependency Injection",
                "Understanding Enterprise SOA",
                "Open-Source ESBs in Action",
                "Activiti in Action",
                "DSLs in Boo: Domain-Specific Languages in .NET",
                "JUnit Recipes",
                "wxPython in Action",
                "Clojure in Action",
                "Scala in Action",
                "Working with Objects",
                "PHP in Action",
                "Secrets of the JavaScript Ninja",
                "Microsoft Office Essentials",
                "Swing",
                "The Awesome Power of Java Beans",
                "Personal Videoconferencing",
                "The Cloud at Your Service",
                "Implementing Elliptic Curve Cryptography",
                "SOA Patterns",
                "Hello World!",
                "SCBCD Exam Study Kit",
                "Portlets in Action",
                "SWT/JFace in Action",
                "OpenCL in Action",
                "Multiprotocol over ATM",
                "Dependency Injection in .NET",
                "Java 3D Programming",
                "Liferay in Action",
                "JSP Tag Libraries",
                "Instant Messaging in Java",
                "Java Applets and Channels Without Programming",
                "PowerShell in Practice",
                "PowerShell and WMI",
                "Making Sense of Java",
                "C++/CLI in Action",
                "C# in Depth",
                "C# in Depth, Second Edition",
                "Magical A-Life Avatars",
                "Becoming Agile",
                "ActiveMQ in Action",
                "Implementing PeopleSoft Financials",
                "SQL Server DMVs in Action",
                "Scala in Depth",
                "JMX in Action",
                "EJB Cookbook",
                "GWT in Action, Second Edition",
                "JUnit in Action, Second Edition",
                "Bitter Java",
                "Bitter EJB",
                "Spring Batch in Action",
                "JDK 1.4 Tutorial",
                "iPhone and iPad in Action",
                "SQL Server 2005 Reporting Services in Action",
                "Ten Years of UserFriendly.Org",
                "Graphics Programming with Perl",
                "RabbitMQ in Action",
                "XDoclet in Action",
                "Spring in Action",
                "Spring in Action, Second Edition",
                "Spring in Action, Third Edition",
                "Spring in Practice",
                "Java 2 Micro Edition",
                "SharePoint 2010 Workflows in Action",
                "SharePoint 2010 Web Parts in Action",
                "C++ Concurrency in Action",
                "Java Servlets by Example",
                "XML Programming with VB and ASP",
                "Oracle8i Database Administration",
                "The Engaging Web",
                "Enterprise OSGi In Action",
                "Ext JS in Action, Second Edition",
                "Android in Action, Third Edition",
                "Arduino in Action",
                "Node.js in Action",
                "Third-Party JavaScript ",
                "Multimedia Computing",
                "Web Development with JavaServer Pages",
                "Up to Speed with Swing",
                "Manager's Guide to Open Source",
                "Programming Web Services with Java",
                "TCP/IP Programming for OS/2",
                "SCWCD Exam Study Kit",
                "Unit Testing in C++",
                "Big Data",
                "CoffeeScript in Action",
                "SQL Server MVP Deep Dives, Volume 2",
                "HTML5 in Action",
                "Java Persistence with Hibernate, Second Edition",
                "Hadoop in Practice",
                "HBase in Action",
                "Flex Mobile in Action",
                "HTML5 for .NET Developers",
                "50 Android Hacks",
                "PowerShell in Depth",
                "Augmented Reality Revealed",
                "Building Well-Structured JavaScript Applications",
                "Linked Data",
                "Mule in Action, Second Edition",
                "Single Page Web Applications",
                "The Art of Unit Testing, Second Edition",
                "Play for Java",
                "Hello World! Second Edition",
                "Dart in Action",
                "Redis in Action",
                "Using the TI-83 Plus/TI-84 Plus",
                "Neo4j in Action",
                "Programming the TI-83 Plus/TI-84 Plus",
                "Functional Programming in Scala",
                "Play for Scala",
                "Node.js in Practice",
                "SonarQube in Action",
                "Windows Store App Development: C# and XAML",
                "Learn Windows IIS in a Month of Lunches",
                "Mondrian in Action",
                "RabbitMQ in Depth",
                "Akka in Action",
                "Extending jQuery",
                "OCA Java SE 7 Programmer I Certification Guide",
                "Kanban in Action",
                "Solr in Action",
                "Making Sense of NoSQL",
                "Jaguar Development with PowerBuilder 7",
                "Grails in Action, Second Edition",
                "Rails 4 in Action",
                "Learn Windows PowerShell in a Month of Lunches, Second Edition",
                "AOP in .NET",
                "Learn PowerShell Toolmaking in a Month of Lunches",
                "CMIS and Apache Chemistry in Action",
                "Action Guide (aka VB .NET)",
                "Learn Active Directory Management in a Month of Lunches",
                "Spring in Action, Fourth Edition",
                "The Mikado Method",
                "The Responsive Web",
                "Fast ASP.NET Websites",
                "SBT in Action",
                "PowerShell Deep Dives",
                "Gradle in Action",
                "Scalatra in Action",
                "AngularJS in Action",
                "Software Development Metrics",
                "F# Deep Dives",
                "C# in Depth, Third Edition",
                "PostGIS in Action, Second Edition",
                "R in Action, Second Edition",
                "The Joy of Clojure, Second Edition",
                "iOS 7 in Action",
                "Hello App Inventor!",
                "Ember.js in Action",
                "Netty in Action",
                "RavenDB in Action",
                "OCP Java SE 7 Programmer II Certification Guide",
                "Backbone.js in Action",
                "Clojure in Action, Second Edition",
                "Practical Data Science with R",
                "ArcGIS Web Development",
                "Elasticsearch in Action",
                "Learn SCCM 2012 in a Month of Lunches",
                "Programming for Musicians and Digital Artists",
                "BDD in Action",
                "Windows Phone 8 in Action",
                "Titanium Alloy in Action",
                "Giraph in Action",
                "The Well-Grounded Rubyist, Second Edition",
                "Go in Action",
                "The Programmer's Guide to Apache Thrift ",
                "Grokking Functional Programming",
                "CORS in Action",
                "Reactive Design Patterns",
                "Storm Applied",
                "Real-World Machine Learning",
                "jQuery UI in Action",
                "Web Components in Action",
                "JavaScript Application Design",
                "Git in Practice",
                "Impala in Action",
                "Java 8 in Action",
                "Elixir in Action",
                "MongoDB in Action, Second Edition",
                "Getting MEAN with Mongo, Express, Angular, and Node",
                "jQuery in Action, Third Edition",
                "D3.js in Action",
                "Learn SQL Server Administration in a Month of Lunches",
                "Geoprocessing with Python",
                "Barcodes with iOS",
                "Chef in Action",
                "Hadoop in Practice, Second Edition",
                "Oculus Rift in Action",
                "OpenStack in Action",
                "PowerShell in Depth, Second Edition",
                "Practical Probabilistic Programming",
                "Unity in Action",
                "Express.js in Action",
                "Learn Git in a Month of Lunches",
                "Understanding SPAs",
                "Aeneid: Selections from Books 1",
                "Eclogues. Georgics. Aeneid: Books 1-6",
                "City Eclogue",
                "The Eclogues and The Georgics",
                "Paul Kirk's Championship Barbecue Sauces:",
                "The Complete Pelican Shakespeare",
                "The Complete Works",
                "Hamlet",
                "The Compleat Works of Wllm",
                "The Pilgrimage: A Contemporary Quest",
                "The Valkyries",
                "Warrior of the Light",
                "The Zahir",
                "By the River Piedra I",
                "The Fifth Mountain",
                "Veronika Decides to Die",
                "Hamlet",
                "Cliffs Notes on Shakespeare's Hamlet",
                "Shakespeare's Hamlet",
                "Hamlet's Mill: An Essay Investigating",
                "History of the Peloponnesian War:",
                "On Justice Power and Human",
                "History of the Peloponnesian War:",
                "The Peloponnesian War",
                "The Peloponnesian War: A New",
                "History of the Peloponnesian War",
                "Thucydides Book 6 Commentary",
                "Euripides I: Alcestis / The",
                "Euripides V: Electra / The",
                "Euripides IV: Rhesus / The",
                "Grief Lessons: Four Plays by",
                "Ten Plays",
                "Euripides III: Hecuba / Andromache",
                "Euripides II: The Cyclops /",
                "Medea and Other Plays",
                "Cyclops / Alcestis / Medea",
                "Medea",
                "The Bacchae and Other Plays",
                "Bakkhai",
                "Plays 1: Medea/The Phoenician Women/Bacchae",
                "The Trojan Women and Hippolytus",
                "The Bacchae of Euripides: A",
                "Orestes and Other Plays",
                "Children of Heracles / Hippolytus",
                "Alcestis",
                "Suppliant Women / Electra /",
                "Medea",
                "Euripides: Medea",
                "CliffsNotes on Euripides' Medea and",
                "Trojan Women / Iphigenia Among",
                "Helen / Phoenician Women /",
                "Euripides: Iphigenia at Aulis (Companions",
                "The Complete Greek Tragedies Volume",
                "Aeschylus I: Oresteia (Agamemnon The",
                "Aeschylus II: The Suppliant Maidens",
                "The Oresteia",
                "The Oresteia: Agamemnon The Libation",
                "Oresteia",
                "Prometheus Bound and Other Plays",
                "The Oresteia",
                "Aeschylus 1: The Oresteia: Agamemnon/The",
                "The Complete Greek Tragedies Volume",
                "Aeschylus: The Oresteia (A Student",
                "The Oresteia: Agamemnon Choephoroe &",
                "Aeschylus 2: The Persians/Seven Against",
                "The Oresteia Trilogy: Agamemnon/The Libation-Bearers/The",
                "The Suppliant Maidens/The Persians/Seven against",
                "Sophocles II: Ajax/Women of Trachis/Electra/Philoctetes",
                "The Oedipus Plays of Sophocles:",
                "The Complete Plays",
                "The Oedipus Cycle: Oedipus Rex",
                "The Three Theban Plays: Antigone",
                "Theban Plays",
                "The Theban Plays (Everyman's Library",
                "Electra and Other Plays",
                "Antigone; Oedipus the Kingn; Electra",
                "Oedipus Rex (The Theban Plays",
                "The Oedipus Plays of Sophocles",
                "Oedipus Rex (Greek and Latin",
                "Oedipus the King",
                "Four Plays: The Clouds/The Birds/Lysistrata/The",
                "Three Plays by Aristophanes: Lysistrata/Women",
                "The Complete Plays",
                "Aristophanes 1: The Acharnians/Peace/Celebrating Ladies/Wealth",
                "Clouds/Wasps/Birds (Aristophanes 1)",
                "Lysistrata and Other Plays",
                "Acharnians",
                "Clouds",
                "Clouds/Wasps/Peace",
                "Three Plays: The Wasps /",
                "Four Comedies: Lysistrata / The",
                "Frogs/Assemblywomen/Wealth (Loeb Classical Library 180)",
                "Cliffs Notes on Aristophanes' Lysistrata",
                "Aristophanes and Athens: An Introduction",
                "Lysistrata",
                "Peace",
                "Lysistrata",
                "The Knights / Peace /",
                "Genres in Dialogue: Plato and",
                "The Curious Incident of the",
                "The Night Gardener",
                "Twelfth Night",
                "Brokeback Mountain",
                "Getting Things Done: The Art",
                "Getting Things Done When You",
                "Formas breves",
                "El último lector",
                "Money to Burn",
                "Respiración artificial",
                "Plata quemada",
                "American Government: Continuity and Change",
                "Essentials of American and Texas",
                "El túnel",
                "The Confessions (Works of Saint",
                "The City of God",
                "The Enchiridion on Faith Hope",
                "Augustine of Hippo: A Biography",
                "On Christian Doctrine",
                "Confessions Books 1-13",
                "Saint Augustine",
                "Augustine: A Very Short Introduction",
                "On Genesis/A Refutation of the",
                "Kitchen Confidential: Adventures in the",
                "Confesiones de un chef",
                "The Metamorphoses of Ovid",
                "Metamorphoses",
                "Metamorphoses",
                "Ovid's Metamorphoses: Books 1-5",
                "Ovid’s Metamorphoses: Books 6-10",
                "Latin Via Ovid: A First",
                "The Art of Love and",
                "The Poems of Exile: Tristia",
                "Metamorphoses: Volume 2 Books IX-XV",
                "Metamorphoses: Volume I Books I-VIII",
                "Practice! Practice!: A Latin Via",
                "Tibullus: A Commentary",
                "Dionysiac Poetics and Euripides' Bacchae",
                "Antigone",
                "Antigone",
                "Object-Oriented Programming in C++",
                "The Iliad",
                "Love Sex & Tragedy: How",
                "Reading Greek Tragedy",
                "Who Needs Greek? Contests in",
                "Foucault's Virginity: Ancient Erotic Fiction",
                "2012: The Return of Quetzalcoatl",
                "Breaking Open the Head: A",
                "Them: Adventures with Extremists",
                "The Men Who Stare at",
                "Guns Germs and Steel: The",
                "Caught Inside: A Surfer's Year",
                "Into the Wild",
                "Wild at Heart: Discovering the",
                "Wild Swans: Three Daughters of",
                "Wild Fire (John Corey #4)",
                "Born to Be Wild",
                "The Call of the Wild",
                "Wild About Books",
                "In Web Design for Libraries",
                "Nickel and Dimed: On (Not)",
                "The History of Sexuality 1:",
                "The History of Sexuality Volume",
                "The History of Sexuality Volume",
                "The Making of Pride and",
                "Pride and Prejudice",
                "Pride & Prejudice",
                "Pride and Prejudice",
                "Pride and Prejudice",
                "Under the Banner of Heaven:",
                "Iceland: Land of the Sagas",
                "Into Thin Air: A Personal",
                "In the Land of White",
                "The World Is Flat: A",
                "La Tierra es plana: Breve",
                "The Avalanche Handbook",
                "Avalanche",
                "Little Women",
                "Little Women (Little Women #1)",
                "Little Women",
                "Little Women",
                "Little Women Little Men Jo's",
                "Little Women",
                "A Tale of Two Cities",
                "A Tale of Two Cities",
                "A Tale of Two Cities:",
                "A Tale of Two Cities",
                "A Tale of Two Cities",
                "Den of Thieves",
                "Den of Thieves (Cat Royal",
                "Charles Dickens: Four Novels: Great",
                "Bleak House",
                "David Copperfield",
                "What Jane Austen Ate and",
                "Charles Dickens",
                "Martin Chuzzlewit",
                "Why Is Sex Fun? The",
                "The Third Chimpanzee: The Evolution",
                "J.K.Rowling",
                "Harry Potter Schoolbooks Box Set:",
                "J.K. Rowling's Harry Potter Novels:",
                "Harry Potter and the Half-Blood",
                "The Santaroga Barrier",
                "The Dosadi Experiment (ConSentiency Universe",
                "The Eyes of Heisenberg",
                "The Birds (Methuen Drama)",
                "The Frogs",
                "Lysistrata",
                "Myths of the Underworld Journey:",
                "Assembly of Women (Literary Classics)",
                "Comoediae 1: Acharenses/Equites/Nubes/Vespae/Pax/Aves",
                "Aristophanes and His Theatre of",
                "Later Novels and Other Writings:",
                "Stories and Early Novels: Pulp",
                "The Lady in the Lake",
                "The High Window (Philip Marlowe",
                "The Simple Art of Murder",
                "The Big Sleep (Philip Marlowe",
                "The Long Goodbye (Philip Marlowe",
                "An Evening of Long Goodbyes",
                "The Long Goodbye: Memories of",
                "Ghost In the Shell 2:",
                "The Long Goodbye (Philip Marlowe",
                "Breaking the Spell: Religion as",
                "Darwin's Dangerous Idea: Evolution and",
                "Freedom Evolves",
                "Brainstorms: Philosophical Essays on Mind",
                "Kinds of Minds: Towards an",
                "Leaps of Faith: Science Miracles",
                "Elbow Room: The Varieties of",
                "The Mind’s I: Fantasies and",
                "The Illustrated A Brief History",
                "A Briefer History of Time",
                "The Universe in a Nutshell",
                "God Created the Integers: The",
                "Stephen Hawking's Universe: The Cosmos",
                "The Future of Spacetime",
                "Stephen Hawking's Universe",
                "The Nature of Space and",
                "The Physics of Star Trek",
                "Falconry & Hawking",
                "The World Treasury of Physics",
                "The Art of Nonfiction: A",
                "The Journals of Ayn Rand",
                "The Fountainhead",
                "The 36-Hour Day: A Family",
                "The 3-Hour Diet: On the",
                "The Last Hours of Ancient",
                "Specimen Days",
                "A Home at the End",
                "Blink: The Power of Thinking",
                "Blink",
                "Blink-182: Tales from Beneath Your",
                "The Complete Novels",
                "The Jane Austen Book Club",
                "Jane Austen: The Complete Novels",
                "Jane Austen's Letters",
                "Persuasion",
                "Tea with Jane Austen",
                "The Old Man and the",
                "Cliffs Notes on Hemingway's The",
                "Flaubert's Parrot",
                "Flaubert in Egypt: A Sensibility",
                "A Sentimental Education",
                "Three Tales",
                "Sentimental Education",
                "The Family Idiot 5: Gustave",
                "Middlesex",
                "Team of Rivals: The Political",
                "John Adams",
                "The John Adams Reader: Eseential",
                "The Letters of John and",
                "Passionate Sage: The Character and",
                "The Portable John Adams",
                "Sex For Dummies",
                "Baby Signing For Dummies",
                "The Feeling Good Handbook",
                "On Death and Dying",
                "Questions and Answers on Death",
                "The Last Dance: Encountering Death",
                "Mahatma Gandhi and His Myths:",
                "The Seven Habits of Highly",
                "The 7 Habits of Highly",
                "Daily Reflections For Highly Effective",
                "Way of the Peaceful Warrior:",
                "Secret of the Peaceful Warrior",
                "It's Not about the Bike:",
                "23 Days in July: Inside",
                "Truman",
                "The Complete Stories of Truman",
                "Breakfast at Tiffany's: A Short",
                "Murder at The Washington Tribune",
                "Murder at Ford's Theatre (Capital",
                "Other Voices Other Rooms",
                "In Cold Blood",
                "Emergence: The Connected Lives of",
                "Emergence: Labeled Autistic",
                "The Emergence of Life on",
                "The Ghost Stories of Edith",
                "The House of Mirth /",
                "Collected Stories 1911-1937",
                "Novellas and Other Writings: Madame",
                "The House of Mirth",
                "Below the Root",
                "The Witches of Worm",
                "The Deeper Meaning of Liff",
                "Dirk Gently's Holistic Detective Agency",
                "The Letters of J.R.R. Tolkien",
                "The History of the Lord",
                "The Languages of Tolkien's Middle-Earth",
                "The Lord of the Rings-",
                "Farmer Giles of Ham",
                "Tandia",
                "Matthew Flinders' Cat",
                "Solomon's Song (The Potato Factory",
                "An Introduction to Old Norse",
                "Cold Counsel: Women in Old",
                "Brave Companions: Portraits in History",
                "Mornings on Horseback: The Story",
                "John Adams",
                "The Johnstown Flood",
                "The Path Between the Seas:",
                "The Bone Collector (Lincoln Rhyme",
                "The Bone Collector's Son",
                "El Coleccionista De Huesos (Lincoln",
                "Moby Dick",
                "Moby-Dick",
                "Moby Dick",
                "Moby-Dick",
                "Herman Melville's Moby-Dick: A Routledge",
                "Moby Dick: or The White",
                "Melville's Moby Dick: An American",
                "Moby Dick: Or the White",
                "Melville and the politics of",
                "Double Tap (Paul Madriani #8)",
                "The List",
                "Witches Abroad (Discworld #12; Witches",
                "The Innocents Abroad",
                "Teaching English Abroad",
                "Theocritus: Select Poems: Select Poems",
                "The Shield. Catalogue of Women.",
                "Death and the King's Horseman",
                "The Time Machine",
                "The Time Machine",
                "The Ultimate Time Machine: A",
                "The Time Machine",
                "The Complete Short Stories",
                "Selected Stories",
                "Tono-Bungay",
                "The Name of the Rose",
                "In the Name of Jesus:",
                "Blood Done Sign My Name:",
                "Blindness",
                "The Gospel According to Jesus",
                "All the Names",
                "The Tale of the Unknown",
                "Baltasar and Blimunda",
                "The Cave",
                "The Stone Raft",
                "The Year of the Death",
                "El hombre duplicado",
                "Ensayo sobre la lucidez",
                "La caverna",
                "The History of the Siege",
                "Las intermitencias de la muerte",
                "The Treasured Writings of Kahlil",
                "The Prophet",
                "A Tear and a Smile",
                "On the Road",
                "On the Road",
                "De Kooning: An American Master",
                "Willem de Kooning: Late Paintings",
                "Aké: The Years of Childhood",
                "Ready for Anything: 52 Productivity",
                "The Facilitator's Book of Questions:",
                "Sun Tzu and the Art",
                "Marketing Warfare",
                "The Tipping Point: How Little",
                "Unleashing the Ideavirus: Stop Marketing",
                "The Innovator's Dilemma: The Revolutionary",
                "Great Expectations",
                "Great Expectations: Authoritative Text Backgrounds",
                "Luther and Erasmus: Free Will",
                "To Kill a Mockingbird",
                "To Kill a Mockingbird",
                "To Kill a Mockingbird",
                "The Wealthy Barber: Everyone's Common-Sense",
                "A Modest Proposal and Other",
                "Gulliver's Travels / A Modest",
                "Empire 2.0: A Modest Proposal",
                "The Bostonians",
                "Novels 1896–1899: The Other House",
                "Novels 1901–1902: The Sacred Fount",
                "Complete Stories 1892–1898",
                "The Canterbury Tales",
                "The Canterbury Tales",
                "The Canterbury Tales (original-spelling edition)",
                "Chaucer's Canterbury Tales (Selected): An",
                "Oxford Guides to Chaucer: The",
                "Love Visions",
                "Chaucer's Canterbury Tales",
                "The Riverside Chaucer",
                "The Portable Chaucer",
                "Salt: A World History",
                "Salt in His Shoes: Michael",
                "The Book of Salt",
                "Cities of Salt (مدن الملح",
                "The Years of Rice and",
                "Illuminations: Essays and Reflections",
                "Saul Steinberg: Illuminations",
                "Advanced Global Illumination",
                "Snow Falling On Cedars",
                "The Lost Boy (Dave Pelzer",
                "Real Boys: Rescuing Our Sons",
                "Microserfs",
                "New Media Language",
                "The Denial of Death",
                "A People's History of the",
                "A People's History of the",
                "A People's History of the",
                "Graphic Design: A Concise History",
                "Immigrant Acts: On Asian American",
                "The Old Way of Seeing:",
                "The Crying of Lot 49",
                "E=mc²: A Biography of the",
                "Passionate Minds",
                "Christian Mythmakers: C.S. Lewis Madeleine",
                "A House Like a Lotus",
                "The Rock That Is Higher:",
                "The Glorious Impossible",
                "A Full House: An Austin",
                "A Circle of Quiet (Crosswicks",
                "The Birth of Tragedy",
                "Birth Of A Tragedy: Kashmir",
                "The Tragedy of Pudd'nhead Wilson/Those",
                "The Tragedy of Pudd'nhead Wilson",
                "Bridge to Terabithia",
                "Literature Circle Guide: Bridge to",
                "Bread and Roses Too",
                "The Invisible Child",
                "A Short History of Decay",
                "Scholar of Decay (Ravenloft #14)",
                "Girl with a Pearl Earring",
                "The Golden Tulip",
                "Burning Bright",
                "Falling Angels",
                "The Virgin Blue",
                "Wenn Engel fallen",
                "Tom Hunter: Living in Hell",
                "Bleach Volume 15",
                "Bleach Volume 01",
                "Bleach Volume 14",
                "Bleach Volume 11",
                "Bleach Volume 12",
                "DEATH NOTE デスノート 1",
                "Death Note Vol. 4: 恋心",
                "Death Note Vol. 3: 激走",
                "Love Artist (Harlequin Romance #2860)",
                "Perfume: The Story of a",
                "Das Parfum. Die Geschichte eines",
                "Three Stories and a Reflection",
                "The Pigeon",
                "The Story of Mr Sommer",
                "Bleach―ブリーチ― 1 [Burīchi 1] (Bleach",
                "Bleach Tome 1: The Death",
                "Escape from Fire Mountain (World",
                "How Angel Peterson Got His",
                "Tucket's Travels: Francis Tucket's Adventures",
                "Chicago Blues: The City and",
                "Winterdance: The Fine Madness of",
                "Brian's Winter",
                "Robinson Crusoe (Robinson Crusoe #1)",
                "Robinson Crusoe",
                "Robinson Crusoe",
                "Robinson Crusoe",
                "Robinson Crusoe",
                "A General History of the",
                "Huck Finn & Tom Sawyer",
                "Huck Finn and Tom Sawyer",
                "Huck Finn/Pudd'nhead Wilson/No 44 Mysterious",
                "The Adventures of Huckleberry Finn",
                "Adventures of Huckleberry Finn",
                "The Wit and Wisdom of",
                "Mark Twain's Helpful Hints for",
                "The Complete Short Stories of",
                "The Autobiography of Mark Twain",
                "Collected Tales Sketches Speeches &",
                "Lost Horizon",
                "Louisa May Alcott's Christmas Treasury",
                "My Secret Garden: Women's Sexual",
                "The Secret Garden",
                "A Little Princess",
                "Waiting for the Party: The",
                "The Secret Garden Cookbook: Recipes",
                "Basic Economics: A Citizen's Guide",
                "Basic Economics: A Common Sense",
                "Black Rednecks and White Liberals",
                "Applied Economics: Thinking Beyond Stage",
                "Knowledge And Decisions",
                "A Conflict of Visions: Ideological",
                "Sir Gawain and the Green",
                "Alcoholics Anonymous",
                "The Twelve Steps & Twelve",
                "The Natural Way to Draw",
                "Natural Health Natural Medicine",
                "The Fixer",
                "The Complete Stories",
                "The Assistant",
                "Conversations with Bernard Malamud (Literary",
                "The Tenants",
                "Enchanted April: Acting Edition",
                "April May und June",
                "A Room with a View",
                "A Room with a View",
                "E.M. Forster: Critical Guidebook",
                "The Longest Journey",
                "Howards End",
                "Maurice",
                "E. M. Forster: A Life",
                "Howards End",
                "The Sixteen Pleasures",
                "Revolutionary Characters: What Made the",
                "The Rescue (Kidnapped #3)",
                "Hunting the Hunter (On the",
                "Public Enemies (On The Run",
                "Runaway Bride",
                "The Bridge over the Drina",
                "Drina Dances in Paris",
                "Drina Ballerina",
                "Le Pont sur la Drina",
                "Drina Dances in Italy",
                "Drina Goes on Tour",
                "Drina Dances in Madeira",
                "Phaedrus/Apology/Crito/Symposium",
                "The Dialogues of Plato Volume",
                "Gorgias/Timaeus",
                "Minor Works: On Colours/On Things",
                "Aristophanes I: Clouds/Wasps/Birds",
                "The Trojan Women",
                "Greek Tragedies Volume 2",
                "Moloka'i (Moloka'i #1)",
                "Teaching with the Brain in",
                "Introducing Mind and Brain (Introducing...)",
                "Eva Luna",
                "The Stories of Eva Luna",
                "Diez Cuentos de Eva Luna",
                "El bosque de los pigmeos",
                "Inés of My Soul",
                "La casa de los espíritus",
                "El plan infinito",
                "El reino del dragón de",
                "City of the Beasts (Eagle",
                "Self",
                "Die Brücke über die Drina",
                "Drina Dances in Switzerland",
                "The Story of Salt",
                "Nonviolence: Twenty-Five Lessons from the",
                "Boogaloo on 2nd Avenue",
                "Cod: A Biography of the",
                "1968: The Year That Rocked",
                "A Chosen Few: The Resurrection",
                "The Basque History of the",
                "The Cod's Tale",
                "Open City 6: The Only",
                "Harry Potter Y La Piedra",
                "Angle of Repose",
                "Don't Make Me Think: A",
                "Girlfriend in a Coma",
                "Corelli's Mandolin",
                "Kiffe Kiffe Tomorrow",
                "Our Kind of People: Inside",
                "The Senator and the Socialite:",
                "Temptations",
                "The Thorn Birds",
                "Caesar (Masters of Rome #5)",
                "Caesar's Women (Masters of Rome",
                "On Off (Carmine Delmonico #1)",
                "Three Complete Novels: Tim/An Indecent",
                "Morgan's Run",
                "The October Horse: A Novel",
                "The First Man in Rome",
                "The Grass Crown (Masters of",
                "Tim",
                "O'Brien's the Things They Carried",
                "The Five People You Meet",
                "The Curious Incident of the",
                "Northern Lights",
                "If I Die in a",
                "Going After Cacciato",
                "In the Lake of the",
                "The Nuclear Age",
                "The Rescue",
                "A Bend in the Road",
                "True Believer (Jeremy Marsh &",
                "Three Weeks With My Brother",
                "The Wedding (The Notebook #2)",
                "El Guardián",
                "Nights in Rodanthe",
                "Message in a Bottle",
                "A Walk to Remember",
                "Icy Sparks",
                "Message in a Bottle",
                "Sugarplums and Scandal (Love at",
                "Special Topics in Calamity Physics",
                "The Dictionary of Corporate Bullshit:",
                "On Truth",
                "Twelve Sharp (Stephanie Plum #12)",
                "Sharp Edges",
                "Mrs. Sharp's Traditions: Reviving Victorian",
                "The Sly Spy (Olivia Sharp",
                "The Green Toenails Gang (Olivia",
                "The Pizza Monster (Olivia Sharp",
                "The Spy Who Barked (Adam",
                "Kare First Love Vol. 9",
                "The World's First Love: Mary",
                "Kare First Love Vol. 10",
                "The Tutor's First Love",
                "First Love",
                "Love @ First Site",
                "First Love Second Chance",
                "The Modern Prince: Charles J.",
                "The Modern Prince and Other",
                "Emily of New Moon (Emily",
                "The Selected Journals Of L.M.",
                "Against the Odds: Tales of",
                "Anne of Avonlea",
                "A Tangled Web",
                "The Complete Anne of Green",
                "Pat of Silver Bush (Pat",
                "Sherlock Holmes: The Complete Novels",
                "The New Annotated Sherlock Holmes:"
        };
        String[] LLanguages = {
                "English", "Spanish", "French", "German", "Mandarin Chinese",
                "Hindi", "Arabic", "Portuguese", "Russian",
                "Japanese", "Javanese", "Tamil", "Turkish", "Tamazight", "Korean", "Urdu", "Italian",
                "Vietnamese", "Persian", "Polish", "Ukrainian",
                "Pashto", "Xiang Chinese", "Malayalam", "Uzbek",
                "Amharic", "Fula", "Romanian", "Oromo", "Kurdish", "Igbo",
                "Azerbaijani", "Awadhi", "Norvetchek", "Irish", "Cebuano", "Dutch"};
        this.Title = LTitles[new Random().nextInt(LTitles.length)];
        this.PublicationYear = Calendar.getInstance().get(Calendar.YEAR) - new Random().nextInt(25);;
        this.Language = LLanguages[new Random().nextInt(LLanguages.length)];
        this.NbPages = ThreadLocalRandom.current().nextInt(50, 501);
        this.idCategory = ThreadLocalRandom.current().nextInt(1, 19);;
        this.idAuthor = ThreadLocalRandom.current().nextInt(0, 300);;;
        this.rating = ThreadLocalRandom.current().nextInt(1, 5);
        this.price = ThreadLocalRandom.current().nextInt(10, 300);
        this.bookimage = ThreadLocalRandom.current().nextInt(1, 2962);
    }

    public int getIdBook() {
        return idBook;
    }

    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String title) {
        Title = title;
    }

    public int getPublicationYear() {
        return PublicationYear;
    }

    public void setPublicationYear(int publicationYear) {
        PublicationYear = publicationYear;
    }

    public String getLanguage() {
        return Language;
    }

    public void setLanguage(String language) {
        Language = language;
    }

    public int getNbPages() {
        return NbPages;
    }

    public void setNbPages(int nbPages) {
        NbPages = nbPages;
    }

    public int getidCategory() {
        return idCategory;
    }

    public void setidCategory(int idcategory) {
        idCategory = idcategory;
    }

    public int getIdAuthor() {
        return idAuthor;
    }

    public void setIdAuthor(int idAuthor) {
        this.idAuthor = idAuthor;
    }


    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public int getBookimage() {
        return bookimage;
    }

    public void setBookimage() { this.bookimage = bookimage; }

}
