version: '4.34'

services:
  web:
    build: .
    container_name: php-apache-web
    ports:
      - "8080:80"
    volumes:
      - .:/srv/http
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: localhost # Link to the MySQL container
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - localhost
    ports:
      - "8081:80"  # Map phpMyAdmin to port 8081 on the host

volumes:
  db_data:
